defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:

development:
  <<: *defaults
  database: myplace_dev


test:
  <<: *defaults
  database:  myplace_test
